// src/components/Tasks/ListTasks.vue
<template>
  <p style="text-align: center">
    <v-select
      v-model="filterContext"
      :items="filterOptions"
      item-title="title"
      item-value="value"
      label="Filter by"
      density="compact"
      variant="outlined"
      hide-details
      style="min-width: 10%; max-width: 12em; display: inline-block; margin-right: 2em"
    />

    <v-text-field
      v-if="filterContext !== 'created_by'"
      v-model="filterParam"
      :label="`Search ${filterContext}`"
      density="compact"
      variant="outlined"
      hide-details
      style="max-width: 18em; display: inline-block"
    />
    <v-select
      v-else
      v-model="filterByUser"
      :items="userOptions"
      item-title="name"
      item-value="id"
      label="Filter by user"
      density="compact"
      variant="outlined"
      hide-details
      clearable
      style="min-width: 10%; max-width: 14em; display: inline-block; margin-right: 2em"
    />
  </p>

  <v-container style="gap: 2em; padding: 1em">
    <div
      v-for="task in filteredTasks"
      :key="task.id"
      class="task-card"
    >
      <span>
        <router-link :to="'/task/view/' + task.id" style="text-decoration: none">
          <b>{{ task.title }}</b>
        </router-link>
      </span>
      <br />
      {{ TypeList[task.type] }}<br />
      {{ StatusList[task.status] }}<br />
      <v-divider />
      <i>Created by <b>{{ task.created_by.name }}</b> on {{ task.created_on }}</i>
      <br />
    </div>

    <v-snackbar v-model="showNotification" location="top right" :timeout="-1">
      <v-alert :type="notificationType" variant="tonal">
        {{ notificationMsg }}
      </v-alert>
    </v-snackbar>
  </v-container>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import ErrorMessages from '../../enums/ErrorMessages'
import StatusList from '../../enums/StatusList'
import TypeList from '../../enums/TypeList'
import { serverHost } from '../../config'

const route = useRoute()

const notificationType = ref('error')
const notificationMsg = ref('')
const showNotification = ref(false)

const tasks = ref([])
const users = ref([])

const filterContext = ref('status')
const filterParam = ref('')
const filterByUser = ref('')

const filterOptions = [
  { title: 'Status', value: 'status' },
  { title: 'Type', value: 'type' },
  { title: 'Created by', value: 'created_by' },
]

const userOptions = computed(() => users.value)

const filterString = computed(() => {
  return route.query.tipo ? '?type=' + route.query.tipo : ''
})

const filteredTasks = computed(() => {
  return tasks.value.filter((filteredTask) => {
    if (filterContext.value !== 'created_by') {
      return String(filteredTask[filterContext.value] || '')
        .toLowerCase()
        .includes(filterParam.value)
    }
    if (filterByUser.value !== '' && filterByUser.value !== null) {
      return String(filteredTask.created_by.id) === String(filterByUser.value)
    }
    return true
  })
})

const handleRequest = () => {
  const token = sessionStorage.getItem('token')

  fetch(serverHost + '/api/task/list' + filterString.value, {
    headers: { Authorization: 'Bearer ' + token },
  })
    .then((response) => response.json())
    .then((data) => {
      tasks.value = data.data.tasks

      const ids = []
      const filteredUsers = []
      data.data.tasks.forEach((task) => {
        if (!ids.includes(task.created_by.id)) {
          ids.push(task.created_by.id)
          filteredUsers.push({ id: task.created_by.id, name: task.created_by.name })
        }
      })
      users.value = filteredUsers
    })
    .catch((err) => {
      const message = err.message !== '' ? err.message : ErrorMessages.DEFAULT_ERROR_MSG
      notificationType.value = 'error'
      showNotification.value = true
      notificationMsg.value = message
    })
}

onMounted(() => {
  handleRequest()
})

watch(
  () => route.query.tipo,
  () => {
    handleRequest()
  }
)
</script>

// src/components/Tasks/ListTasks.jsx
import { Alert, Grid, Snackbar, TextField, Divider, Container, MenuItem } from "@mui/material";
import { React, useState, useEffect } from "react";
import { Link, useSearchParams, useNavigate } from "react-router-dom";

import ErrorMessages from "../../enums/ErrorMessages";
import StatusList from "../../enums/StatusList";
import TypeList from "../../enums/TypeList";

function ListTasks()
{
    const [notificationType, setNotificationType] = useState("");
    const [notificationMsg, setNotificationMsg] = useState("");
    const [showNotification, setShowNotification] = useState(false);

    const navigate = useNavigate();
    const [searchParams] = useSearchParams();

    const [tasks, setTasks] = useState([]);
    const [users, setUsers] = useState([]);

    const [filterContext, setFilterContext] = useState("status");
    const [filterParam, setFilterParam] = useState('');
    const [filterByUser, setFilterByUser] = useState("");

    const filterString = (searchParams.get('tipo') === null) ? '' : '?type='+searchParams.get('tipo');
    const host = process.env.REACT_APP_SERVER_HOST;
    const token = sessionStorage.getItem("token");

    if (!token) {
        navigate("/login");
    }

    const handleRequest = () => {
        fetch( host + '/api/task/list' + filterString, { headers: { 'Authorization': 'Bearer ' + token } } )
        .then((response) => response.json())
        .then((data) => {
            setTasks(data.data.tasks);
            
            var ids = [];
            var filteredUsers = [];
            data.data.tasks.filter((task) => {
                if (!ids.includes(task.created_by.id)){
                    ids.push(task.created_by.id)
                    filteredUsers.push({ id: task.created_by.id, name: task.created_by.name })
                }
            })
            setUsers(filteredUsers);
        })
        .catch((err) => {
            var message = (err.message !== '') ? err.message : ErrorMessages.DEFAULT_ERROR_MSG;
            setNotificationType('error')
            setShowNotification(true)
            setNotificationMsg(message)
        });
    }

    useEffect(() => {
        handleRequest();
    }, []);

    return(
        <>
            <p style={{textAlign: 'center'}}>
                <TextField label="Filter by" size="small" style={{minWidth: "10%", marginRight: '2em'}}
                    onChange={
                        (event) => {
                            setFilterContext(event.target.value);
                        }
                    } select
                >
                    <MenuItem value="status">Status</MenuItem>
                    <MenuItem value="type">Type</MenuItem>
                    <MenuItem value="created_by">Created by</MenuItem>
                </TextField>
                
                { filterContext !== "created_by" ? (
                    <TextField label={`Search ${filterContext}`} size="small" onChange={(event) => { setFilterParam(event.target.value); }} />
                ) : (
                    <TextField label="Filter by user" size="small" style={{minWidth: "10%", marginRight: '2em'}}
                        onChange={
                            (event) => {
                                setFilterByUser(event.target.value);
                            }
                        } select
                    >
                        <MenuItem value="">&nbsp;</MenuItem>
                        {
                            users.map((user) => {
                                return <MenuItem value={user.id}>{user.name}</MenuItem>
                            })
                        }
                    </TextField>
                )}
            </p>
            <Container style={{gap: '2em', padding:'1em'}} >
                {
                    tasks.filter((filteredTask) => {
                        if(filterContext !== "created_by") {
                            return filteredTask[filterContext].toLowerCase().includes(filterParam);
                        }
                        if (filterByUser !== "") {
                            return filteredTask.created_by.id === filterByUser;
                        }
                        return filteredTask;
                    })
                    .map((task) => {
                        return (
                            <Grid  sx={{ borderRadius: 2}} style={{marginBottom: '0.5em', backgroundColor: 'white', padding: '1em'}} key={task.id}>
                                <span>
                                    <Link to={'/task/view/' + task.id} style={{textDecoration: 'none' }}> <b>{task.title}</b> </Link>
                                </span><br/>
                                { TypeList[task.type] }<br/>
                                { StatusList[task.status] }<br/>
                                <Divider />
                                <i>Created by <b>{task.created_by.name}</b> on {task.created_on}</i> <br/>
                            </Grid>
                        );
                    })
                }
                <Snackbar
                    anchorOrigin={{ vertical: 'top', horizontal: 'right'}}
                    open={showNotification}
                >
                    <Alert severity={notificationType} sx={{ width: '100%' }}>
                        {notificationMsg}
                    </Alert>
                </Snackbar>
            </Container>
        </>
    )
}

export default ListTasks;
