// src/components/Tasks/EditTask.vue
<template>
  <div v-if="task.id">
    <table style="width: 100%; border-collapse: collapse">
      <tbody>
        <tr>
          <td style="padding: 8px">
            <h2 style="display: inline-block">{{ task.title }}</h2>&nbsp;&nbsp;&nbsp;
            <v-btn
              style="height: 2.2em; margin-top: -0.6em; background-color: lightskyblue; color: black; font-size: x-small"
              variant="flat"
              @click="handleUpdate(task.id)"
            >
              Update
            </v-btn>
            <br /><b>Created On:</b> {{ task.created_on }} <b>By</b> {{ createdBy.name }}<br />
          </td>
        </tr>
        <tr>
          <td style="padding: 8px">
            <v-text-field
              id="title"
              v-model="title"
              label="Title"
              variant="outlined"
              density="compact"
              class="mb-2"
            />
            <v-select
              id="status"
              v-model="status"
              :items="statusOptions"
              item-title="title"
              item-value="value"
              label="Status"
              variant="outlined"
              density="compact"
              class="mb-2"
            />
            <v-select
              id="type"
              v-model="type"
              :items="typeOptions"
              item-title="title"
              item-value="value"
              label="Type"
              variant="outlined"
              density="compact"
              class="mb-2"
            />
            <v-textarea
              id="description"
              v-model="description"
              label="Description"
              variant="outlined"
              rows="10"
            />
          </td>
        </tr>
      </tbody>
    </table>

    <v-snackbar v-model="showNotification" location="top right" :timeout="-1">
      <v-alert :type="notificationType" variant="tonal">
        {{ notificationMsg }}
      </v-alert>
    </v-snackbar>
  </div>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import ErrorMessages from '../../enums/ErrorMessages'
import { serverHost } from '../../config'

const router = useRouter()
const route = useRoute()
const token = sessionStorage.getItem('token')

const notificationType = ref('error')
const notificationMsg = ref('')
const showNotification = ref(false)

const task = ref({})
const createdBy = ref({})

const title = ref(null)
const description = ref(null)
const status = ref(null)
const type = ref(null)

const statusOptions = [
  { title: 'Open', value: 'open' },
  { title: 'In Dev', value: 'in_dev' },
  { title: 'Blocked', value: 'blocked' },
  { title: 'In QA', value: 'in_qa' },
]

const typeOptions = [
  { title: 'Feature', value: 'feature' },
  { title: 'Bugfix', value: 'bugfix' },
  { title: 'Hotfix', value: 'hotfix' },
]

const showError = (err) => {
  const message = err.message !== '' ? err.message : ErrorMessages.DEFAULT_ERROR_MSG
  notificationType.value = 'error'
  showNotification.value = true
  notificationMsg.value = message
}

const buildRequestObject = () => {
  const requestObj = {}

  if (title.value !== null) {
    requestObj.title = title.value
  }

  if (description.value !== null) {
    requestObj.description = description.value
  }

  if (status.value !== null) {
    requestObj.status = status.value
  }

  if (type.value !== null) {
    requestObj.type = type.value
  }

  return JSON.stringify(requestObj)
}

const handleUpdate = (taskId) => {
  fetch(serverHost + '/api/task/update/' + taskId, {
    headers: {
      accept: 'application/json',
      'content-type': 'application/json',
      Authorization: 'Bearer ' + token,
    },
    method: 'PUT',
    body: buildRequestObject(),
  })
    .then((response) => response.json())
    .then(() => {
      router.push('/task/view/' + taskId)
    })
    .catch(showError)
}

onMounted(() => {
  fetch(serverHost + '/api/task/view/' + route.params.id, {
    headers: { Authorization: 'Bearer ' + token },
  })
    .then((response) => response.json())
    .then((data) => {
      task.value = data.data
      createdBy.value = data.data.created_by
      title.value = data.data.title
      description.value = data.data.description
      status.value = data.data.status
      type.value = data.data.type
    })
    .catch(showError)
})
</script>

// src/components/EditTask.jsx
import { Alert, Button, Grid, Snackbar, TextField, TableBody, TableCell, TableContainer, TableRow, MenuItem } from "@mui/material";
import { React, useState, useEffect } from "react";
import { useNavigate } from "react-router";

import ErrorMessages from "../enums/ErrorMessages";

function EditTask()
{
    const navigate = useNavigate();

    const [notificationType, setNotificationType] = useState("");
    const [notificationMsg, setNotificationMsg] = useState("");
    const [showNotification, setShowNotification] = useState(false);

    const [task, setTask] = useState([]);
    const [createdBy, setCreatedBy] = useState([]);

    const [title, setTitle] = useState(null);
    const [description, setDescription] = useState(null);
    const [status, setStatus] = useState(null);
    const [type, setType] = useState(null);

    const host = process.env.REACT_APP_SERVER_HOST;
    const token = sessionStorage.getItem("token");

    useEffect(() => {
        fetch(host + '/api/task/view/' + window.location.pathname.split("/")[3] , { headers: { 'Authorization': 'Bearer ' + token } })
        .then((response) => response.json())
        .then((data) => {
            setTask(data.data);
            setCreatedBy(data.data.created_by);
        })
        .catch((err) => {
            var message = (err.message !== '') ? err.message : ErrorMessages.DEFAULT_ERROR_MSG;
            setNotificationType('error')
            setShowNotification(true)
            setNotificationMsg(message)
        });
    }, []);

    const handleUpdate = (taskId) => 
    {
        fetch(host + '/api/task/update/' + taskId, 
        {
            headers: {
                accept: 'application/json',
                'content-type': 'application/json',
                'Authorization': 'Bearer ' + token
            }, 
            method: 'PUT', 
            body: buildRequestObject()
        })
        .then((response) => response.json())
        .then(() => {
            navigate("/task/view/" + taskId);
        })
        .catch((err) => {
            var message = (err.message !== '') ? err.message : ErrorMessages.DEFAULT_ERROR_MSG;
            setNotificationType('error')
            setShowNotification(true)
            setNotificationMsg(message)
        });
    }

    const buildRequestObject = () =>
    {
        var requestObj = {};

        if (title !== null) {
            requestObj.title = title;
        }

        if (description !== null) {
            requestObj.description = description;
        }

        if (status !== null) {
            requestObj.status = status;
        }

        if (type !== null) {
            requestObj.type = type;
        }

        return JSON.stringify(requestObj);
    }

    return (
        <Grid key={task.id} >
            <TableContainer >
                <TableBody>
                    <TableRow>
                        <TableCell>
                            <h2 style={{ display: 'inline-block' }}>{task.title}</h2>&nbsp;&nbsp;&nbsp;
                            <Button style={{ height: '2.2em', marginTop: '-0.6em', backgroundColor: 'lightskyblue', color: 'black' }}>
                                <a href="#" style={{textDecoration: 'none', fontSize:'x-small', color: 'black'}} onClick={() => { handleUpdate(task.id) }} >Update</a>
                            </Button>
                            <br/><b>Created On:</b> {task.created_on} <b>By</b> {createdBy.name}<br/>
                        </TableCell>
                    </TableRow>
                    <TableRow>
                        <TableCell>
                            <TextField id="title" label="Title" margin="dense" size="small" defaultValue={task.title}  fullWidth
                                onChange={
                                    (event) => {
                                        setTitle(event.target.value);
                                    }
                                }/>
                            <TextField id="status" label="Status" margin="dense" size="small" defaultValue={task.status} fullWidth select 
                                onChange={
                                    (event) => {
                                        setStatus(event.target.value);
                                    }
                                }>
                                <MenuItem value={"open"}>Open</MenuItem>
                                <MenuItem value={"in_dev"}>In Dev</MenuItem>
                                <MenuItem value={"blocked"} selected={true} >Blocked</MenuItem>
                                <MenuItem value={"in_qa"}>In QA</MenuItem>
                            </TextField>
                            <TextField id="type" label="Type" margin="dense" size="small" defaultValue={task.type} fullWidth
                                onChange={
                                    (event) => {
                                        setType(event.target.value);
                                    }
                                } select
                                >
                                    <MenuItem value={"feature"} selected={true}>Feature</MenuItem>
                                    <MenuItem value={"bugfix"}>Bugfix</MenuItem>
                                    <MenuItem value={"hotfix"}>Hotfix</MenuItem>
                            </TextField>
                            <TextField id="description" defaultValue={task.description} label="Description" multiline rows={10} fullWidth 
                                onChange={
                                    (event) => {
                                        setDescription(event.target.value);
                                    }
                                }/>
                        </TableCell>
                    </TableRow>
                </TableBody>
            </TableContainer>

            <Snackbar
                anchorOrigin={{ vertical: 'top', horizontal: 'right'}}
                open={showNotification}
            >
                <Alert severity={notificationType} sx={{ width: '100%' }}>
                    {notificationMsg}
                </Alert>
            </Snackbar>
        </Grid>
    );
    
}

export default EditTask;
